/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useCallback } from 'react';
import { SearchPanel, OSINT_TOOLS } from './components/SearchPanel';
import { GraphView } from './components/GraphView';
import { DetailsPanel } from './components/DetailsPanel';
import { OSINTGraph, OSINTNode, OSINTMode, gatherIntelligence } from './services/geminiService';
import { Shield, Activity, Database, Settings, Menu, X, Terminal, ExternalLink, Download, FileText, Cpu, Globe, Zap, AlertTriangle, ArrowRight } from 'lucide-react';
import { jsPDF } from 'jspdf';
import { TooltipProvider } from './components/ui/tooltip';
import { motion, AnimatePresence } from 'motion/react';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from './components/ui/sheet';

import { Toaster } from './components/ui/sonner';
import { toast } from 'sonner';

export default function App() {
  const [allResults, setAllResults] = useState<Partial<Record<OSINTMode, OSINTGraph>>>({});
  const [selectedNode, setSelectedNode] = useState<OSINTNode | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [isSidebarOpen, setIsSidebarOpen] = useState(true);
  const [isDetailsOpen, setIsDetailsOpen] = useState(false);
  const [hasSearched, setHasSearched] = useState(false);
  const [logs, setLogs] = useState<string[]>([]);
  const [currentMode, setCurrentMode] = useState<OSINTMode>('maltego');
  const [showSplash, setShowSplash] = useState(true);

  const graphData = allResults[currentMode] || { nodes: [], links: [] };

  const addLog = useCallback((message: string) => {
    setLogs(prev => [...prev, `[${new Date().toLocaleTimeString()}] ${message}`].slice(-50));
  }, []);

  const openUrl = (url: string) => {
    const link = document.createElement('a');
    link.href = url;
    link.target = '_blank';
    link.rel = 'noopener noreferrer';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const downloadReport = useCallback(() => {
    if (graphData.nodes.length === 0) {
      toast.error("No intelligence data available to export.");
      return;
    }

    const targetNode = graphData.nodes[0]; // Usually the first one is the target
    const timestamp = new Date().toLocaleString();
    
    let report = `# NEXUS OSINT Intelligence Report\n`;
    report += `Generated: ${timestamp}\n`;
    report += `Target: ${targetNode.label} (${targetNode.type})\n`;
    report += `Investigation Mode: ${currentMode.toUpperCase()}\n\n`;
    
    report += `## Summary\n`;
    report += `- Total Entities Found: ${graphData.nodes.length}\n`;
    report += `- Total Relationships Mapped: ${graphData.links.length}\n\n`;
    
    report += `## Discovered Entities\n\n`;
    graphData.nodes.forEach(node => {
      report += `### ${node.label}\n`;
      report += `- **Type:** ${node.type}\n`;
      report += `- **ID:** ${node.id}\n`;
      if (node.data && Object.keys(node.data).length > 0) {
        report += `- **Metadata:**\n`;
        Object.entries(node.data).forEach(([key, value]) => {
          report += `  - ${key}: ${typeof value === 'object' ? JSON.stringify(value) : value}\n`;
        });
      }
      report += `\n`;
    });
    
    report += `## Relationship Map\n\n`;
    graphData.links.forEach(link => {
      const source = graphData.nodes.find(n => n.id === link.source)?.label || link.source;
      const target = graphData.nodes.find(n => n.id === link.target)?.label || link.target;
      report += `- [${source}] --(${link.label || 'connected'})--> [${target}]\n`;
    });
    
    report += `\n## Investigation Logs\n\n`;
    logs.forEach(log => {
      report += `${log}\n`;
    });
    
    report += `\n---\n*Report generated by Nexus OSINT Intelligence Engine*`;

    const blob = new Blob([report], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `nexus_report_${targetNode.label.replace(/\s+/g, '_').toLowerCase()}_${new Date().getTime()}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    
    toast.success("Intelligence report downloaded successfully.");
  }, [graphData, logs, currentMode]);

  const downloadPDF = useCallback(() => {
    if (graphData.nodes.length === 0) {
      toast.error("No intelligence data available to export.");
      return;
    }

    const doc = new jsPDF();
    const targetNode = graphData.nodes[0];
    const timestamp = new Date().toLocaleString();
    let yPos = 20;

    // Title
    doc.setFontSize(22);
    doc.setTextColor(20, 184, 166); // Primary color
    doc.text("NEXUS OSINT Intelligence Report", 20, yPos);
    yPos += 10;

    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated: ${timestamp}`, 20, yPos);
    yPos += 15;

    // Summary Section
    doc.setFontSize(16);
    doc.setTextColor(0, 0, 0);
    doc.text("Investigation Summary", 20, yPos);
    yPos += 8;
    
    doc.setFontSize(11);
    doc.text(`Target: ${targetNode.label}`, 25, yPos); yPos += 6;
    doc.text(`Type: ${targetNode.type}`, 25, yPos); yPos += 6;
    doc.text(`Mode: ${currentMode.toUpperCase()}`, 25, yPos); yPos += 6;
    doc.text(`Total Entities: ${graphData.nodes.length}`, 25, yPos); yPos += 6;
    doc.text(`Relationships: ${graphData.links.length}`, 25, yPos); yPos += 15;

    // Entities Section
    doc.setFontSize(16);
    doc.text("Discovered Entities", 20, yPos);
    yPos += 10;

    graphData.nodes.forEach((node, index) => {
      if (yPos > 270) {
        doc.addPage();
        yPos = 20;
      }

      doc.setFontSize(12);
      doc.setFont("helvetica", "bold");
      doc.text(`${index + 1}. ${node.label}`, 20, yPos);
      yPos += 6;

      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text(`Type: ${node.type}`, 25, yPos);
      yPos += 5;

      if (node.data && Object.keys(node.data).length > 0) {
        Object.entries(node.data).forEach(([key, value]) => {
          if (yPos > 280) {
            doc.addPage();
            yPos = 20;
          }
          const valStr = typeof value === 'object' ? JSON.stringify(value) : String(value);
          const text = `${key}: ${valStr}`;
          const splitText = doc.splitTextToSize(text, 160);
          doc.text(splitText, 30, yPos);
          yPos += (splitText.length * 5);
        });
      }
      yPos += 5;
    });

    // Breach Section
    const breaches = graphData.nodes.filter(n => n.type === 'breach');
    if (breaches.length > 0) {
      if (yPos > 250) {
        doc.addPage();
        yPos = 20;
      }
      yPos += 10;
      doc.setTextColor(239, 68, 68); // Red color for danger
      doc.setFontSize(16);
      doc.text("CRITICAL: DATA BREACH INTELLIGENCE", 20, yPos);
      doc.setTextColor(0, 0, 0);
      yPos += 10;

      breaches.forEach((breach, index) => {
        if (yPos > 280) {
          doc.addPage();
          yPos = 20;
        }
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.text(`[!] ${breach.label}`, 20, yPos);
        yPos += 6;
        
        if (breach.data && Object.keys(breach.data).length > 0) {
          doc.setFontSize(10);
          doc.setFont("helvetica", "normal");
          Object.entries(breach.data).forEach(([key, value]) => {
            const text = `${key}: ${value}`;
            const splitText = doc.splitTextToSize(text, 160);
            doc.text(splitText, 25, yPos);
            yPos += (splitText.length * 5);
          });
        }
        yPos += 5;
      });
    }

    // Logs Section
    if (yPos > 250) {
      doc.addPage();
      yPos = 20;
    }
    yPos += 10;
    doc.setFontSize(16);
    doc.text("Investigation Logs", 20, yPos);
    yPos += 10;

    doc.setFontSize(8);
    doc.setFont("courier", "normal");
    logs.forEach(log => {
      if (yPos > 280) {
        doc.addPage();
        yPos = 20;
      }
      const splitLog = doc.splitTextToSize(log, 170);
      doc.text(splitLog, 20, yPos);
      yPos += (splitLog.length * 4);
    });

    doc.save(`nexus_report_${targetNode.label.replace(/\s+/g, '_').toLowerCase()}.pdf`);
    toast.success("PDF Report generated successfully.");
  }, [graphData, logs, currentMode]);

  const handleSearch = useCallback(async (target: string, mode: OSINTMode, details?: any) => {
    setIsLoading(true);
    setHasSearched(true);
    setLogs([]);
    setAllResults({});
    setSelectedNode(null);
    setCurrentMode(mode);
    addLog(`Initializing ${mode.toUpperCase()} engine...`);
    addLog(`Target identified: ${target}`);
    
    const modes: OSINTMode[] = ['maltego', 'epieos', 'maigret', 'googledorking'];
    
    try {
      addLog(`Executing parallel intelligence gathering across all nodes...`);
      
      const promises = modes.map(async (m) => {
        try {
          addLog(`[${m.toUpperCase()}] Engine engaged...`);
          const result = await gatherIntelligence(target, m, details);
          return { mode: m, result };
        } catch (err) {
          console.error(`Engine ${m} failed:`, err);
          addLog(`[${m.toUpperCase()}] Engine failed.`);
          return { mode: m, result: { nodes: [], links: [], intelligenceLogs: [`Error: ${m} engine failed.`] } };
        }
      });

      const resultsArray = await Promise.all(promises);
      const newResults: Partial<Record<OSINTMode, OSINTGraph>> = {};
      
      resultsArray.forEach(({ mode: m, result }) => {
        newResults[m] = result;
        if (result.intelligenceLogs) {
          result.intelligenceLogs.forEach(log => addLog(`[${m.toUpperCase()}] ${log}`));
        }
      });

      setAllResults(newResults);
      
      const currentResult = newResults[mode];
      if (currentResult && currentResult.nodes.length > 0) {
        setSelectedNode(currentResult.nodes[0]);
        addLog(`SUCCESS: Multi-engine scan complete.`);
        toast.success(`Investigation complete. All tools ready.`);
      } else {
        toast.warning("Investigation complete, but some engines returned no data.");
      }
    } catch (error: any) {
      addLog(`CRITICAL ERROR: Multi-engine investigation failed.`);
      console.error("Investigation failed", error);
      
      const errorMsg = error?.message || "";
      if (errorMsg.includes("RESOURCE_EXHAUSTED") || errorMsg.includes("429")) {
        toast.error("API Quota exceeded. Please wait a minute before trying again.");
      } else {
        toast.error("Investigation failed. Please check your connection.");
      }
    } finally {
      setIsLoading(false);
    }
  }, [addLog]);

  const handleNodeClick = useCallback((node: OSINTNode) => {
    setSelectedNode(node);
    if (window.innerWidth < 1280) {
      setIsDetailsOpen(true);
    }
  }, []);

  return (
    <TooltipProvider>
      <div className="flex flex-col h-screen w-screen bg-background overflow-hidden selection:bg-primary/30 cyber-grid">
        <Toaster position="top-right" theme="dark" />
        
        {/* Top Ticker */}
        <div className="ticker-wrap h-8 flex items-center z-50">
          <div className="ticker text-[10px] font-mono text-primary flex items-center gap-8">
            <span className="flex items-center gap-2"><AlertTriangle className="w-3 h-3" /> THREAT: RANSOMWARE GROUP CLAIMS ATTACK ON HEALTHCARE PROVIDER</span>
            <span className="flex items-center gap-2"><Zap className="w-3 h-3" /> SYSTEM: NEURAL OSINT ENGINE ENGAGED</span>
            <span className="flex items-center gap-2"><Activity className="w-3 h-3" /> STATUS: AI ENGINE ONLINE - HIBP NODE ACTIVE</span>
            <span className="flex items-center gap-2"><Globe className="w-3 h-3" /> NETWORK: GLOBAL INTELLIGENCE NODES SYNCHRONIZED</span>
          </div>
        </div>

        <div className="flex flex-1 overflow-hidden">
          {/* Sidebar - Only show if searched or explicitly toggled */}
          <AnimatePresence mode="wait">
            {isSidebarOpen && hasSearched && (
              <motion.aside
                initial={{ x: -320 }}
                animate={{ x: 0 }}
                exit={{ x: -320 }}
                transition={{ type: 'spring', damping: 20, stiffness: 100 }}
                className="w-80 border-r border-border bg-black/80 backdrop-blur-xl flex flex-col z-20"
              >
                <div className="p-6 flex items-center gap-3 border-b border-border">
                  <div className="w-10 h-10 rounded-lg bg-primary/20 flex items-center justify-center border border-primary/50 glow-red">
                    <Shield className="w-6 h-6 text-primary" />
                  </div>
                  <div>
                    <h1 className="text-lg font-display tracking-tighter leading-none text-primary">AEGIS</h1>
                    <p className="text-[8px] font-mono text-muted-foreground uppercase tracking-[0.2em] mt-1">Forensic Intelligence Node</p>
                  </div>
                </div>

                <div className="flex-1 overflow-y-auto p-6">
                  <SearchPanel 
                    onSearch={handleSearch} 
                    isLoading={isLoading} 
                    currentMode={currentMode}
                    onModeChange={setCurrentMode}
                  />
                </div>

                <div className="p-4 border-t border-border bg-secondary/10">
                  <div className="flex items-center justify-between text-[10px] font-mono text-muted-foreground uppercase tracking-widest">
                    <div className="flex items-center gap-2">
                      <Activity className="w-3 h-3 text-green-500" />
                      <span>System Online</span>
                    </div>
                    <span>v4.0.0</span>
                  </div>
                </div>
              </motion.aside>
            )}
          </AnimatePresence>

          {/* Main Content */}
          <main className="flex-1 flex flex-col relative min-w-0">
            {/* Header */}
            <header className="h-16 border-b border-border flex items-center justify-between px-8 bg-black/40 backdrop-blur-md z-10">
              <div className="flex items-center gap-6">
                {!hasSearched && (
                  <div className="flex items-center gap-3">
                    <div className="w-8 h-8 rounded bg-primary/20 flex items-center justify-center border border-primary/40">
                      <Shield className="w-5 h-5 text-primary" />
                    </div>
                    <div>
                      <h1 className="text-sm font-display tracking-tight text-primary">AEGIS <span className="text-foreground/50">SYSTEM</span></h1>
                      <p className="text-[7px] font-mono text-muted-foreground uppercase tracking-widest">Forensic Intelligence Node V4.0</p>
                    </div>
                  </div>
                )}
                {hasSearched && (
                  <button
                    onClick={() => setIsSidebarOpen(!isSidebarOpen)}
                    className="p-2 hover:bg-secondary rounded-md transition-colors border border-border"
                  >
                    {isSidebarOpen ? <X className="w-4 h-4" /> : <Menu className="w-4 h-4" />}
                  </button>
                )}
                <div className="h-4 w-[1px] bg-border" />
                <div className="flex items-center gap-2 text-[10px] font-mono text-muted-foreground uppercase tracking-widest">
                  <Terminal className="w-3 h-3" />
                  <span>{hasSearched ? '/investigation/active' : '/system/standby'}</span>
                </div>
              </div>

              <div className="flex items-center gap-8">
                <div className="hidden md:flex items-center gap-6 text-[9px] font-mono uppercase tracking-widest">
                  <div className="flex flex-col items-end">
                    <span className="text-muted-foreground">Darkside Protocol</span>
                    <span className="text-foreground/40 flex items-center gap-1.5"><div className="w-1 h-1 rounded-full bg-foreground/20" /> Standby</span>
                  </div>
                  <div className="flex flex-col items-end">
                    <span className="text-muted-foreground">AI Engine</span>
                    <span className="text-green-500 flex items-center gap-1.5"><div className="w-1 h-1 rounded-full bg-green-500 animate-pulse" /> Online</span>
                  </div>
                  <div className="flex flex-col items-end">
                    <span className="text-muted-foreground">HIBP Node</span>
                    <span className="text-green-500 flex items-center gap-1.5"><div className="w-1 h-1 rounded-full bg-green-500" /> Active</span>
                  </div>
                </div>

                <div className="flex items-center gap-2">
                  {graphData.nodes.length > 0 && (
                    <div className="flex items-center gap-2">
                      <button 
                        onClick={downloadReport}
                        className="flex items-center gap-2 px-3 py-1.5 bg-secondary hover:bg-secondary/80 text-foreground rounded-md transition-all text-[10px] font-bold uppercase tracking-widest border border-border"
                      >
                        <Download className="w-3 h-3" />
                        <span>MD</span>
                      </button>
                      <button 
                        onClick={downloadPDF}
                        className="flex items-center gap-2 px-3 py-1.5 bg-primary/10 hover:bg-primary/20 text-primary rounded-md transition-all text-[10px] font-bold uppercase tracking-widest border border-primary/20"
                      >
                        <FileText className="w-3 h-3" />
                        <span>PDF Report</span>
                      </button>
                    </div>
                  )}
                </div>
              </div>
            </header>

            {/* Content Area */}
            <div className="flex-1 relative overflow-hidden">
              <AnimatePresence mode="wait">
                {showSplash ? (
                  <motion.div
                    key="splash"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    exit={{ opacity: 0, scale: 1.1, filter: 'blur(20px)' }}
                    transition={{ duration: 0.8, ease: "easeInOut" }}
                    className="absolute inset-0 z-[100] bg-background flex flex-col items-center justify-center p-6 text-center overflow-hidden"
                  >
                    {/* Background Elements */}
                    <div className="absolute inset-0 opacity-20 pointer-events-none">
                      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[800px] bg-primary/20 rounded-full blur-[120px] animate-pulse" />
                      <div className="absolute top-0 left-0 w-full h-full cyber-grid opacity-30" />
                    </div>

                    <motion.div
                      initial={{ y: 40, opacity: 0 }}
                      animate={{ y: 0, opacity: 1 }}
                      transition={{ delay: 0.2, duration: 0.6 }}
                      className="relative z-10 space-y-12 max-w-3xl"
                    >
                      <div className="space-y-4">
                        <div className="flex justify-center mb-8">
                          <motion.div 
                            animate={{ rotate: 360 }}
                            transition={{ duration: 20, repeat: Infinity, ease: "linear" }}
                            className="w-24 h-24 rounded-2xl bg-primary/10 border border-primary/40 flex items-center justify-center glow-red"
                          >
                            <Shield className="w-12 h-12 text-primary" />
                          </motion.div>
                        </div>
                        <h1 className="text-8xl md:text-9xl font-display tracking-tighter leading-none uppercase">
                          AEGIS<br />
                          <span className="text-gradient-red">SYSTEM</span>
                        </h1>
                        <p className="text-muted-foreground text-xs font-mono uppercase tracking-[0.4em] opacity-60">
                          Forensic Intelligence & Neural OSINT Node
                        </p>
                      </div>

                      <div className="pt-8">
                        <button
                          onClick={() => {
                            setShowSplash(false);
                            setHasSearched(true);
                          }}
                          className="group relative px-12 py-5 bg-primary/10 hover:bg-primary/20 text-primary border border-primary/50 rounded-full font-display text-xl uppercase tracking-[0.3em] transition-all hover:scale-105 active:scale-95 glow-red"
                        >
                          <span className="relative z-10 flex items-center gap-4">
                            Initialize System <ArrowRight className="w-6 h-6 group-hover:translate-x-2 transition-transform" />
                          </span>
                          <div className="absolute inset-0 rounded-full bg-primary/20 blur-xl opacity-0 group-hover:opacity-100 transition-opacity" />
                        </button>
                      </div>

                      <div className="grid grid-cols-3 gap-8 pt-16 opacity-40">
                        <div className="space-y-1">
                          <p className="text-[10px] font-mono uppercase tracking-widest text-primary">Protocol</p>
                          <p className="text-[8px] font-mono uppercase">Neural-Link v4.0</p>
                        </div>
                        <div className="space-y-1">
                          <p className="text-[10px] font-mono uppercase tracking-widest text-primary">Status</p>
                          <p className="text-[8px] font-mono uppercase">Encrypted / Secure</p>
                        </div>
                        <div className="space-y-1">
                          <p className="text-[10px] font-mono uppercase tracking-widest text-primary">Uptime</p>
                          <p className="text-[8px] font-mono uppercase">99.99% Operational</p>
                        </div>
                      </div>
                    </motion.div>

                    {/* Corner Accents */}
                    <div className="absolute top-12 left-12 w-16 h-16 border-t-2 border-l-2 border-primary/20" />
                    <div className="absolute top-12 right-12 w-16 h-16 border-t-2 border-r-2 border-primary/20" />
                    <div className="absolute bottom-12 left-12 w-16 h-16 border-b-2 border-l-2 border-primary/20" />
                    <div className="absolute bottom-12 right-12 w-16 h-16 border-b-2 border-r-2 border-primary/20" />
                  </motion.div>
                ) : (
                  <motion.div
                    key="app-content"
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    transition={{ duration: 0.5 }}
                    className="h-full w-full"
                  >
                    {isLoading && (
                      <div className="absolute inset-0 z-50 bg-black/80 backdrop-blur-md flex items-center justify-center">
                        <div className="flex flex-col items-center gap-8">
                          <div className="relative">
                            <div className="w-24 h-24 rounded-full border-2 border-primary/10 border-t-primary animate-spin" />
                            <div className="absolute inset-0 flex items-center justify-center">
                              <Cpu className="w-8 h-8 text-primary animate-pulse" />
                            </div>
                          </div>
                          <div className="space-y-3 text-center">
                            <p className="text-lg font-display text-primary tracking-widest uppercase animate-pulse">
                              {isLoading ? 'Executing Multi-Engine OSINT Protocol' : 'Scanning Digital Footprint'}
                            </p>
                            <div className="flex items-center justify-center gap-4 text-[10px] font-mono text-muted-foreground uppercase tracking-[0.3em]">
                              <span className="flex items-center gap-1.5"><div className="w-1 h-1 rounded-full bg-primary animate-ping" /> Neural Link Active</span>
                              <span className="flex items-center gap-1.5"><div className="w-1 h-1 rounded-full bg-primary animate-ping" /> Data Siphoning</span>
                            </div>
                          </div>
                        </div>
                      </div>
                    )}

                    {graphData.nodes.length > 0 ? (
                      <GraphView 
                        data={graphData} 
                        onNodeClick={handleNodeClick} 
                        selectedNodeId={selectedNode?.id}
                      />
                    ) : (
                      <div className="absolute inset-0 flex flex-col items-center justify-center text-center p-12 space-y-6">
                        <div className="w-24 h-24 rounded-full border-2 border-dashed border-primary/20 flex items-center justify-center animate-pulse">
                          <Shield className="w-12 h-12 text-primary/40" />
                        </div>
                        <div className="max-w-md space-y-2">
                          <h2 className="text-2xl font-display uppercase tracking-widest text-primary">
                            {logs.length === 0 ? 'System Standby' : 'No Intelligence Found'}
                          </h2>
                          <p className="text-muted-foreground text-xs font-mono uppercase tracking-widest opacity-60">
                            {logs.length === 0 
                              ? 'Awaiting target identification. Use the sidebar to initialize a forensic scan.' 
                              : 'The investigation returned no public data for this target. Try a different identifier.'}
                          </p>
                        </div>
                        {logs.length === 0 && (
                          <div className="flex items-center gap-4 pt-4">
                            <div className="flex items-center gap-2 px-3 py-1 border border-border rounded text-[8px] font-mono uppercase text-muted-foreground">
                              <div className="w-1 h-1 rounded-full bg-green-500" />
                              Neural Link Ready
                            </div>
                            <div className="flex items-center gap-2 px-3 py-1 border border-border rounded text-[8px] font-mono uppercase text-muted-foreground">
                              <div className="w-1 h-1 rounded-full bg-green-500" />
                              Maigret Engine Online
                            </div>
                          </div>
                        )}
                      </div>
                    )}
                  </motion.div>
                )}
              </AnimatePresence>
            </div>

            {/* Terminal Log */}
            {hasSearched && (
              <div className="h-48 border-t border-border bg-black/60 backdrop-blur-xl font-mono text-[10px] p-6 overflow-hidden flex flex-col">
                <div className="flex items-center justify-between mb-4">
                  <div className="flex items-center gap-2 text-primary uppercase tracking-[0.3em]">
                    <Terminal className="w-3 h-3" />
                    <span>System Console</span>
                  </div>
                  <div className="flex items-center gap-4 text-muted-foreground/40">
                    <span>Buffer: 1024KB</span>
                    <span>Encryption: AES-256</span>
                  </div>
                </div>
                <div className="flex-1 overflow-y-auto space-y-1.5 scrollbar-hide">
                  {logs.length > 0 ? (
                    logs.map((log, i) => {
                      const urlRegex = /(https?:\/\/[^\s]+)/g;
                      const parts = log.split(urlRegex);
                      return (
                        <div key={i} className="flex gap-3 items-start group">
                          <span className="text-primary/40 shrink-0 mt-0.5">❯</span>
                          <span className="text-muted-foreground group-hover:text-foreground transition-colors">
                            {parts.map((part, index) => 
                              urlRegex.test(part) ? (
                                <button 
                                  key={index} 
                                  onClick={() => openUrl(part)}
                                  className="text-primary hover:underline bg-transparent border-none p-0 cursor-pointer"
                                >
                                  {part}
                                </button>
                              ) : part
                            )}
                          </span>
                        </div>
                      );
                    })
                  ) : (
                    <div className="text-muted-foreground/30 italic">Waiting for system commands...</div>
                  )}
                </div>
              </div>
            )}
          </main>

          {/* Right Panel (Details) */}
          {hasSearched && (
            <aside className="w-80 border-l border-border bg-black/80 backdrop-blur-xl hidden xl:flex flex-col">
              <DetailsPanel node={selectedNode} />
            </aside>
          )}

          {/* Mobile Details Sheet */}
          <Sheet open={isDetailsOpen} onOpenChange={setIsDetailsOpen}>
            <SheetContent side="right" className="w-[90vw] sm:w-[400px] p-0 bg-card border-l border-border">
              <DetailsPanel node={selectedNode} />
            </SheetContent>
          </Sheet>
        </div>
      </div>
    </TooltipProvider>
  );
}
